apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deploy-2022bcd0033
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: face_recognition_attendance-backend
        imagePullPolicy: Never  #  Prevent pulling from Docker Hub
        ports:
        - containerPort: 5000
        env:
          - name: DATABASE_URL
            # value: "postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@$(POSTGRES_HOST):$(POSTGRES_PORT)/$(POSTGRES_DB)"
            value: "postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@db-service:5432/attendance1_db"
        envFrom:
          - configMapRef:
              name: db-configmap-2022bcd0033
          - secretRef:
              name: db-secret-2022bcd0033
