apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deploy-2022bcd0033
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: akshatt123/backend-image:v2
        imagePullPolicy: Always
        # image: face_recognition_attendance-backend
        # imagePullPolicy: Never #  Prevent pulling from Docker Hub
        command: ["/bin/bash", "-c"]
        args:
          - source activate face_recog_env && python app.py
        ports:
        - containerPort: 5000
        env:
        - name: DATABASE_URL
          value: "postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@db-service:5432/attendance1_db"
        envFrom:
        - configMapRef:
            name: db-configmap-2022bcd0033
        - secretRef:
            name: db-secret-2022bcd0033


